### ISSUE TITLE
Questions about how to use the model

### ISSUE THREAD

**Issue by YCaigogogo** [SeanLee97/AnglE#18]
Dear author, thank you for your excellent work. I am now looking to measure the semantic similarity between multiple answers generated by a llm and the ground truth answer. Can I directly use your model to extract features from both the answers generated by the large model and the real answer, and then calculate their cosine similarity as the score for their semantic similarity match? Will the performance of STS be affected?

**Comment by SeanLee97** [comment]
hi @YCaigogogo , thanks for following our work.

1) You can try to use [UAE (non-Retrieval Purposes)](https://github.com/SeanLee97/AnglE?tab=readme-ov-file#uae) to generate features for semantic similarity. 
2) Of course, you can use cosine similarity. It will not affect the performance.

**Comment by YCaigogogo** [comment]
Thank you for reply. I would like to ask what is the max sequence length of UAE?

**Comment by SeanLee97** [comment]
@YCaigogogo 512

**Comment by SeanLee97** [comment]
i'll close this issue. If you have new problems, you can reopen it.
