### ISSUE TITLE
[Bug] Stuck before trainer.train()

### ISSUE THREAD

**Issue by mengyao00** [SeanLee97/AnglE#23]
Hello, I cannot run examples/Angle-ATEC.ipynb, `angle.fit()` output nothing and GPUs are not working. 
Might be version issue, my environment: `Successfully installed bitsandbytes-0.41.3.post2 boltons-23.1.1 peft-0.7.1 tokenizers-0.15.0 transformers-4.36.2`

**Comment by mengyao00** [comment]
I change requirements.txt to transformers==4.32.1, still not working

**Comment by mengyao00** [comment]
`Successfully installed accelerate-0.25.0 bitsandbytes-0.41.3.post2 boltons-23.1.1 datasets-2.16.0 dill-0.3.7 huggingface-hub-0.20.1 multiprocess-0.70.15 peft-0.7.1 pyarrow-hotfix-0.6 safetensors-0.4.1 tokenizers-0.13.3 transformers-4.32.1 xxhash-3.4.1` works for me finally.

**Comment by SeanLee97** [comment]
Thanks for your debugging!
