### ISSUE TITLE
How to set labels for contradict pairs

### ISSUE THREAD

**Issue by mengyao00** [SeanLee97/AnglE#26]
Snli dataset contains contradict pairs, they define labels:
`label: an integer whose value may be either 0, indicating that the hypothesis entails the premise, 1, indicating that the premise and hypothesis neither entail nor contradict each other, or 2, indicating that the hypothesis contradicts the premise. Dataset instances which don't have any gold label are marked with -1 label. Make sure you filter them before starting the training using datasets.Dataset.filter.`
 If I want to use AngLE to fine-tune on those kind of dataset, Should I set -1 for contradict pairs?

**Comment by SeanLee97** [comment]
@mengyao00 In our practice, we set 0 and 1 for the `contradict` and `entailment` labels, respectively. BTW, we do not use the neutral and -1 labels for training. We think they are noise.
