### ISSUE TITLE
How to finetune NLI model

### ISSUE THREAD

**Issue by mdabedr** [SeanLee97/AnglE#29]
Hi, could you please give me an overview of how to fine-tune an NLI model? Namely:
* Which file to fine-tune
* Possible prompts and commands, values of w or any relevant details

**Comment by SeanLee97** [comment]
Hi, it is recommended to read this doc: https://github.com/SeanLee97/AnglE/tree/main/examples/NLI

I will add more docs later.

**Comment by mdabedr** [comment]
So I have to train the angle model before I can fine-tune it for the dataset I have in mind?

**Comment by SeanLee97** [comment]
If you have prepared the NLI datasets, you can fine-tune the model using [`angle-trainer`](https://github.com/SeanLee97/AnglE?tab=readme-ov-file#custom-train)
