### ISSUE TITLE
Compare with M3E

### ISSUE THREAD

**Issue by wqw547243068** [SeanLee97/AnglE#3]
Have you include M3E model as a comparison ?
- [m3e-base](https://huggingface.co/moka-ai/m3e-base) released in about June 2023
- ![image](https://github.com/SeanLee97/AnglE/assets/3257257/7835f1c0-a250-4b7c-9df4-717b9f2fac67)

**Comment by SeanLee97** [comment]
Hi @wqw547243068, thanks for following our work.
I know that m3e is a well-known Chinese text embedding model. However, our paper mainly focused on the English benchmark, so we didn't do any comparison with m3e. Nevertheless, we are working on Chinese text embedding and plan to release our Chinese embedding models in this repository. Welcome to follow us!

**Comment by SeanLee97** [comment]
Hi @wqw547243068, we have released our Chinese pretrained model. 
You can check it now: https://github.com/SeanLee97/AnglE/blob/main/README_zh.md
