### ISSUE TITLE
What similarity metric should I use to measure semantic similarity between two sentences?

### ISSUE THREAD

**Issue by zachares** [SeanLee97/AnglE#42]
In the paper, at training time, it appears that you treat embeddings as a vectors of real numbers which is used to calculate cosine similarity and also as vectors of complex numbers which is used to calculate the angle between the two vectors to measure similarity. At inference time, what similarity metric should I use measure semantic similarity?

**Comment by SeanLee97** [comment]
@zachares hi, you can use cosine or L2 in the inference stage.

**Comment by zachares** [comment]
Thank you!
