### ISSUE TITLE
A little doubt about the paper

### ISSUE THREAD

**Issue by Night-Quiet** [SeanLee97/AnglE#55]
![26e3cf3d01db433d58e90a5ebb402f8](https://github.com/SeanLee97/AnglE/assets/73934131/6f338cb2-8147-427f-86c0-9b9efd6fb8e1)
From a code perspective, the paper concludes by adding up all values of the complex loss function
![bd67d34543e5c8bf0fe30ebd95e4d1d](https://github.com/SeanLee97/AnglE/assets/73934131/e9ca5c1d-cfba-4f28-b524-44b00f3e0b07)
This is a normal complex division formula and transformation. The purpose of the paper is to obtain the content of the red box.
But you ultimately add up, as shown in the following figure:
![0657161fd4f4f17275191040b84bf55](https://github.com/SeanLee97/AnglE/assets/73934131/05f3ca05-1b6c-4c21-8b6c-9c517fb9ee27)
Is this the desired result of the paper? May I ask if you can tell me?, thank you.

**Comment by Night-Quiet** [comment]
不过这似乎确实能缓解饱和区的梯度计算.
![image](https://github.com/SeanLee97/AnglE/assets/73934131/a1c29549-c8c9-49aa-b9c9-7b1a83cf50fe)

**Comment by SeanLee97** [comment]
hi @Night-Quiet, sorry for the delayed reply. 

Thank you for providing the clear formula derivation in polar coordinates. It appears to be correct.

To accumulate the angle differences, we sum them up. In polar coordinates, the result indeed $\sqrt{2}\sin(\Delta)$, where $\Delta = \theta_i - \theta_j + \frac{\pi}{4}$. 
But for polar coordinates, supposed $\sin(\Delta)=x$, the desired result should be $\Delta = arcsin(x)$. 
It is hard to implement this in code. Thus, in this paper, we use an approximate calculation method for the angle difference, as demonstrated in the paper, taking practical considerations into account. Following this approach, the operation `sum(y_pred)` serves as a pooling operation, which can be a `mean` or other types of pooling operation. This pooling step is necessary to compute the final loss.

The reason for computing the normalized angle difference is to **create a more intuitive similarity measurement than cos**. In this context, a smaller angle difference indicates greater similarity.

**Comment by Night-Quiet** [comment]
Thank you for your reply. I think I understand what you mean.
