### ISSUE TITLE
Unversioned PEFT Dependency Prevents Model from Loading

### ISSUE THREAD

**Issue by jambonne** [SeanLee97/AnglE#66]
A recent update to PEFT [deprecates and removes](https://github.com/huggingface/peft/pull/1573) references to `prepare_model_for_8bit_training`. Since `AnglE`'s dependencies are unversioned and it references the deprecated method [here](https://github.com/SeanLee97/AnglE/blob/main/angle_emb/angle.py#L33), the model breaks when its constructor is invoked.

**Comment by ganeshkrishnan1** [comment]
You can install older version of PEFT to fix this temporarily 

`pip install peft==0.7.1
`

**Comment by SeanLee97** [comment]
Thank you! I will update the code to support the latest peft.

**Comment by SeanLee97** [comment]
@ganeshkrishnan1 fixed this issue in `angle_emb==0.3.10`
