### ISSUE TITLE
About angle-bert-base-uncased-nli-en-v1 evaluation issues

### ISSUE THREAD

**Issue by Tffffboys** [SeanLee97/AnglE#68]
When I use angle-bert-base-uncased-nli-en-v1 to evaluate STS performance, I find that it is inconsistent with the original report.

![1711711412953](https://github.com/SeanLee97/AnglE/assets/43122884/93f6a334-50f4-43c4-8efe-696c05e7efda)

![1711711836452](https://github.com/SeanLee97/AnglE/assets/43122884/1844827c-bd08-4ed2-9b7b-e0d00e6ae2de)

The command line I use:
```
python eval_nli.py 
--model_name_or_path /home/whzhu_st/Model/angle-bert-base-uncased-nli-en-v1  
--task_set sts 
--pooling_strategy cls_avg
```

Enviroment:
```
torch 1.13.1
transformer 4.38.1
V100 GPU
```

So is this result acceptable within the error range or is there something wrong with my command?

**Comment by SeanLee97** [comment]
Hi @Tffffboys , the inconsistency arises from the differences in pooling implementation between the newer and older versions. To resolve this, you can consider downgrading the angle_emb to `0.1.1`. Below are the results using angle_emb==0.1.1

```
+-------+-------+-------+-------+-------+--------------+-----------------+-------+
| STS12 | STS13 | STS14 | STS15 | STS16 | STSBenchmark | SICKRelatedness |  Avg. |
+-------+-------+-------+-------+-------+--------------+-----------------+-------+
| 75.26 | 85.61 | 80.64 | 86.36 | 82.51 |    85.64     |      80.99      | 82.43 |
+-------+-------+-------+-------+-------+--------------+-----------------+-------+
```

**Comment by SeanLee97** [comment]
> +-------+-------+-------+-------+-------+--------------+-----------------+-------+

But its performance (82.43) is higher than the original report (82.37) ...

It is a long time ago, maybe I mistakenly uploaded a newer model to HF. I forgot which specific model achieved 82.37 performance😂

**Comment by Tffffboys** [comment]
> Hi @Tffffboys , the inconsistency arises from the differences in pooling implementation between the newer and older versions. To resolve this, you can consider downgrading the angle_emb to `0.1.1`. Below are the results using angle_emb==0.1.1
> 
> ```
> **+-------+-------+-------+-------+-------+--------------+-----------------+-------+**
> | STS12 | STS13 | STS14 | STS15 | STS16 | STSBenchmark | SICKRelatedness |  Avg. |
> +-------+-------+-------+-------+-------+--------------+-----------------+-------+
> | 75.26 | 85.61 | 80.64 | 86.36 | 82.51 |    85.64     |      80.99      | 82.43 |
> +-------+-------+-------+-------+-------+--------------+-----------------+-------+
> ```

Thank you for your reply

**Comment by Tffffboys** [comment]
> But its performance (82.43) is higher than the original report (82.37) ...
> 
> It is a long time ago, maybe I mistakenly uploaded a newer model to HF. I forgot which specific model achieved 82.37 performance😂

😂
